import JSZip from 'jszip';
import { SemanticColor } from './assignRoles';
import { generateTokensCss } from './generateTokensCss';
import { generateTailwindConfig } from './generateTailwindConfig';
import { generateTokensJson } from './generateTokensJson';

export async function downloadZip(colors: SemanticColor[]) {
  const zip = new JSZip();

  zip.file('tokens.css', generateTokensCss(colors));
  zip.file('tailwind.config.js', generateTailwindConfig(colors));
  zip.file('tokens.json', generateTokensJson(colors));
  
  const readme = `# Image to Design Tokens

Here are your extracted design tokens! 

## Files included:
- **tokens.css**: CSS custom properties for native web projects.
- **tailwind.config.js**: A ready-to-use Tailwind CSS theme configuration.
- **tokens.json**: A Style Dictionary compatible JSON file.

*Note: The spacing, typography, and border radius tokens are standardized defaults generated by our heuristic v1 engine. We currently extract colors directly from your image.*
`;

  zip.file('README.md', readme);

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = 'image-to-tokens.zip';
  document.body.appendChild(a);
  a.click();
  
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}
